- name: "Ensure dependencies are installed"
  apt: >
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
    - fontconfig
    - libfontconfig1
    - libfreetype6
    - libpng12-0
    - libxrender1
    - xfonts-base
    - xfonts-75dpi
  tags:
    - wkhtmltopdf
    - pkgs

- name: "Ensure libjpeg dependencies are installed"
  apt: >
    name={{ item }}
    state=present
  with_items:
    - libjpeg8
  when: ansible_distribution_release == "wheezy"
  tags:
    - wkhtmltopdf
    - pkgs

- name: "Ensure libjpeg dependencies are installed"
  apt: >
    name={{ item }}
    state=present
  with_items:
    - libjpeg62-turbo
  when: ansible_distribution_release == "jessie"
  tags:
    - wkhtmltopdf
    - pkgs

- name: "Ensure wkhtmltopdf is installed"
  apt: pkg=wkhtmltopdf state=latest
